### ISSUE TITLE
 EarlyStopping counter?

### ISSUE THREAD

**Issue by fywang12** [Andy-Border/HGSL#1]
Hello,
excuse me, i have a question to ask for your help
when i ran the 'train.py' in my pycharm, i found each Epoch follewed by 'EarlyStopping counter:...' ,what is that mean?

**Comment by AndyJZhao** [comment]
For all baselines and HGSL, we use an EarlyStopper to tune the "epoch" parameter on the validation set. 
You can take a closer look at the code for more details.
