### ISSUE TITLE
Adaption

### ISSUE THREAD

**Issue by bourne-3** [Andy-Border/HGSL#2]
Your job is great. I would like to ask if this method is suitable for multimodal sentiment analysis?(There exist three modality, eg Audio, text and video.And the data appear heterogeneous nature)

**Comment by AndyJZhao** [comment]
Thank you for the kind words. However, for simplification, HGSL is designed to handle the common case of a heterogeneous graph, where a heterogeneous graph is composed of multiple types of nodes and links (with one modality of feature for each type). Nevertheless, if you are trying to mine the potential graph structure generated by intra- and inter-modality of node features, a possible way is to design different metric learning layers and apply channel attention for aggregation.
