### ISSUE TITLE
Threshold Setting and the labeled data

### ISSUE THREAD

**Issue by zhoushengisnoob** [Andy-Border/HGSL#3]
Dear Authors:
    I have two questions about the experiment.
    (1) Given a new dataset, how to set the threshold for different graph construction?
    (2) In the experimental results, why the number of train + val + test set is not equal to the number of nodes? Are the test data randomly selected?
    Thanks :)

**Comment by AndyJZhao** [comment]
Hi,
A1. The threshold should be carefully tuned, e.g. using grid search.
A2. You are describing the case that not all nodes are labeled, which is quite common in the semi-supervised setting. The test nodes is randomly selected.

**Comment by zhoushengisnoob** [comment]
Hi,
About A2, I am not concering about not all nodes are labeled. Instead, I am wondering why the (#train + #val + #test) < #nodes. In a common semi-supervised setting, all the nodes are splitted into train/val/test and ( #train + #val + #test) = #nodes

**Comment by AndyJZhao** [comment]
> Hi,
> About A2, I am not concering about not all nodes are labeled. Instead, I am wondering why the (#train + #val + #test) < #nodes. In a common semi-supervised setting, all the nodes are splitted into train/val/test and ( #train + #val + #test) = #nodes

Could you be more specific on this question? For example, what does #nodes stand for? The number of all labeled nodes or number of all nodes? Which dataset you are concerning? 
P.S. In a common heterogeneous graph node classification task, only one type of nodes (e.g. author in DBLP, paper in ACM, business in Yelp) is labeled, therefore the number of labeled nodes is less than the number of nodes of labeled type.

**Comment by zhoushengisnoob** [comment]
> > Hi,
> > About A2, I am not concering about not all nodes are labeled. Instead, I am wondering why the (#train + #val + #test) < #nodes. In a common semi-supervised setting, all the nodes are splitted into train/val/test and ( #train + #val + #test) = #nodes
> 
> Could you be more specific on this question? For example, what does #nodes stand for? The number of all labeled nodes or number of all nodes? Which dataset you are concerning?
> P.S. In a common heterogeneous graph node classification task, only one type of nodes (e.g. author in DBLP, paper in ACM, business in Yelp) is labeled, therefore the number of labeled nodes is less than the number of nodes of labeled type.

OK，Thanks for your explanation:)
