### ISSUE TITLE
A question about yelp data set

### ISSUE THREAD

**Issue by huafeihuang** [Andy-Border/HGSL#5]
Hello, I have read your paper and am very interested. The node features of the yelp data set are constructed by the word bag vector of keywords, but I don’t know where the keywords in the data set are. I hope to find the original (with key Word) data set, can you help me？
There are where I can find the current data source:
https://github.com/librahu/HeGAN 
https://github.com/Andy-Border/HGSL 
https://github.com/dingdanhao110/Conch 
https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding

but now I can not find the keyword in business (or feature).....\thanks a lot!

**Comment by AndyJZhao** [comment]
> Hello, I have read your paper and am very interested. The node features of the yelp data set are constructed by the word bag vector of keywords, but I don’t know where the keywords in the data set are. I hope to find the original (with key Word) data set, can you help me？ There are where I can find the current data source: https://github.com/librahu/HeGAN https://github.com/Andy-Border/HGSL https://github.com/dingdanhao110/Conch https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding
> 
> but now I can not find the keyword in business (or feature).....\thanks a lot!

Hi Huafei,

Thanks for your interest in our work. 

I don't know the exact source of the word features. Plus, there exist many versions of the Yelp dataset. However, I assume some of the versions were converted from an old dataset dated back to [the data source SemRec](https://github.com/zzqsmall/SemRec/tree/master/data). I hope you may find this link helpful

Best regards,
Jianan

**Comment by huafeihuang** [comment]
> > Hello, I have read your paper and am very interested. The node features of the yelp data set are constructed by the word bag vector of keywords, but I don’t know where the keywords in the data set are. I hope to find the original (with key Word) data set, can you help me？ There are where I can find the current data source: https://github.com/librahu/HeGAN https://github.com/Andy-Border/HGSL https://github.com/dingdanhao110/Conch https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding
> > but now I can not find the keyword in business (or feature).....\thanks a lot!
> 
> Hi Huafei,
> 
> Thanks for your interest in our work.
> 
> I don't know the exact source of the word features. Plus, there exist many versions of the Yelp dataset. However, I assume some of the versions were converted from an old dataset dated back to [the data source SemRec](https://github.com/zzqsmall/SemRec/tree/master/data). I hope you may find this link helpful
> 
> Best regards, Jianan

Thank you very much for your help!  I believe it will deepen my understanding of Yelp dataset. My sincere wishes!
