### ISSUE TITLE
A question about DBLP dataset

### ISSUE THREAD

**Issue by eddiegaoo** [Andy-Border/HGSL#6]
Dear HGSL authors,

I find that the DBLP dataset you used in your paper does not include term nodes.
<img width="447" alt="截屏2022-02-27 23 16 15" src="https://user-images.githubusercontent.com/67420785/155888162-6423ed30-75f5-490f-89fc-04eecfffba45.png">
Is there any reason to do so? I think there are about 8000 term nodes in DBLP dataset used by HAN, MAGNN and other paper as well. I am a little bit confused.

Look forward to your reply!

**Comment by AndyJZhao** [comment]
Hi, as far as I can remember, I was following the settings of GTN [1] where DBLP has no term nodes. You may add term nodes alternatively in your work.

P.S. the term nodes are known to be less useful compared to other types.

[1] Yun, S.; Jeong, M.; Kim, R.; Kang, J.; and Kim, H. J. 2019. Graph Transformer Networks. In NIPS

**Comment by eddiegaoo** [comment]
> Hi, as far as I can remember, I was following the settings of GTN [1] where DBLP has no term nodes. You may add term nodes alternatively in your work.
> 
> P.S. the term nodes are known to be less useful compared to other types.
> 
> [1] Yun, S.; Jeong, M.; Kim, R.; Kang, J.; and Kim, H. J. 2019. Graph Transformer Networks. In NIPS

Many thanks for the reply! I will close this issue.
